  - name: app setup
    include_role: 
      name: common
      tasks_from: app-setup 

  - name: nodejs
    include_role: 
      name: common
      tasks_from: nodejs
  
  
  - name: copying mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
    
  - name: install mongo client
    ansible.builtin.command: dnf install mongodb-mongosh -y

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.srikeshrobot.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  
  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.srikeshrobot.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0
